print("Programa para calcular area de um quadrado para depois mostrar o dobro da area para o usuario")
aquad = float( input("Digite um lado do quadrado: "))
lquad = (aquad * aquad)
print("Area do Quadrado:", lquad)
print("dobrar a area do quadrado com o resultado anterior que é igual a:", aquad)
dlquad = (lquad * 2)
print("resultado do dobro do quadrado:", dlquad)